// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: libs/rpc/proto/stream.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamInfoItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StreamInfoItem) Reset() {
	*x = StreamInfoItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_rpc_proto_stream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamInfoItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoItem) ProtoMessage() {}

func (x *StreamInfoItem) ProtoReflect() protoreflect.Message {
	mi := &file_libs_rpc_proto_stream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoItem.ProtoReflect.Descriptor instead.
func (*StreamInfoItem) Descriptor() ([]byte, []int) {
	return file_libs_rpc_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamInfoItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StreamInfoItem) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type StreamInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *StreamInfoItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *StreamInfoRequest) Reset() {
	*x = StreamInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_rpc_proto_stream_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoRequest) ProtoMessage() {}

func (x *StreamInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_libs_rpc_proto_stream_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoRequest.ProtoReflect.Descriptor instead.
func (*StreamInfoRequest) Descriptor() ([]byte, []int) {
	return file_libs_rpc_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamInfoRequest) GetItem() *StreamInfoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type StreamInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *StreamInfoItem `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *StreamInfoResponse) Reset() {
	*x = StreamInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_libs_rpc_proto_stream_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfoResponse) ProtoMessage() {}

func (x *StreamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_libs_rpc_proto_stream_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfoResponse.ProtoReflect.Descriptor instead.
func (*StreamInfoResponse) Descriptor() ([]byte, []int) {
	return file_libs_rpc_proto_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamInfoResponse) GetItem() *StreamInfoItem {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_libs_rpc_proto_stream_proto protoreflect.FileDescriptor

var file_libs_rpc_proto_stream_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e,
	0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x3e, 0x0a, 0x11, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x22, 0x3f, 0x0a, 0x12, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x32, 0xd7, 0x01, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x41, 0x0a, 0x06, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x18,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12, 0x42, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65,
	0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x03, 0x5a, 0x01, 0x2f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_libs_rpc_proto_stream_proto_rawDescOnce sync.Once
	file_libs_rpc_proto_stream_proto_rawDescData = file_libs_rpc_proto_stream_proto_rawDesc
)

func file_libs_rpc_proto_stream_proto_rawDescGZIP() []byte {
	file_libs_rpc_proto_stream_proto_rawDescOnce.Do(func() {
		file_libs_rpc_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(file_libs_rpc_proto_stream_proto_rawDescData)
	})
	return file_libs_rpc_proto_stream_proto_rawDescData
}

var file_libs_rpc_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_libs_rpc_proto_stream_proto_goTypes = []interface{}{
	(*StreamInfoItem)(nil),     // 0: proto.StreamInfoItem
	(*StreamInfoRequest)(nil),  // 1: proto.StreamInfoRequest
	(*StreamInfoResponse)(nil), // 2: proto.StreamInfoResponse
}
var file_libs_rpc_proto_stream_proto_depIdxs = []int32{
	0, // 0: proto.StreamInfoRequest.item:type_name -> proto.StreamInfoItem
	0, // 1: proto.StreamInfoResponse.item:type_name -> proto.StreamInfoItem
	1, // 2: proto.StreamService.List:input_type -> proto.StreamInfoRequest
	1, // 3: proto.StreamService.Record:input_type -> proto.StreamInfoRequest
	1, // 4: proto.StreamService.Route:input_type -> proto.StreamInfoRequest
	2, // 5: proto.StreamService.List:output_type -> proto.StreamInfoResponse
	2, // 6: proto.StreamService.Record:output_type -> proto.StreamInfoResponse
	2, // 7: proto.StreamService.Route:output_type -> proto.StreamInfoResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_libs_rpc_proto_stream_proto_init() }
func file_libs_rpc_proto_stream_proto_init() {
	if File_libs_rpc_proto_stream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_libs_rpc_proto_stream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamInfoItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libs_rpc_proto_stream_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_libs_rpc_proto_stream_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_libs_rpc_proto_stream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_libs_rpc_proto_stream_proto_goTypes,
		DependencyIndexes: file_libs_rpc_proto_stream_proto_depIdxs,
		MessageInfos:      file_libs_rpc_proto_stream_proto_msgTypes,
	}.Build()
	File_libs_rpc_proto_stream_proto = out.File
	file_libs_rpc_proto_stream_proto_rawDesc = nil
	file_libs_rpc_proto_stream_proto_goTypes = nil
	file_libs_rpc_proto_stream_proto_depIdxs = nil
}
